"""Cấu hình cố định cho ứng dụng giám sát miền Bắc."""

APP_NAME = "TOMS SLA MB"
APP_SLUG = "TOMS-SLA-MB"
APP_DATA_ENV = "TOMS_SLA_MB_DATA_DIR"
TELEGRAM_TOKEN_ENV = "TOMS_SLA_MB_TELEGRAM_BOT_TOKEN"
TELEGRAM_CHAT_ENV = "TOMS_SLA_MB_TELEGRAM_GROUP_CHAT_ID"
SERVICE_CATALOG_API_URL = "https://script.google.com/macros/s/AKfycbwsTQZcKTaEwGwUQgJNjNPGPnn3wgyiStC3j8Er588imXzEFvQtqGJL-NLLXv0BRRXv0w/exec"
UNIT_LABEL = "Phòng HTKH Miền Bắc (VIP 1)"
